export default {
  slots: {},
  utterances: [
    'Am Wochenende besuche ich eine Feier was darf ich anlegen',
    'Am Wochenende besuche ich eine Feier was darf ich anziehen',
    'Am Wochenende besuche ich eine Feier was darf ich kleiden',
    'Am Wochenende besuche ich eine Feier was darf ich tragen',
    'Am Wochenende besuche ich eine Feier was darf ich umbinden',
    'Am Wochenende besuche ich eine Feier was darf ich umhängen',
    'Am Wochenende besuche ich eine Feier was darf ich überstreifen',
    'Am Wochenende besuche ich eine Feier was darf ich überwerfen',
    'Am Wochenende besuche ich eine Feier was darf ich überziehen',
    'Am Wochenende besuche ich eine Feier was kann ich anlegen',
    'Am Wochenende besuche ich eine Feier was kann ich anziehen',
    'Am Wochenende besuche ich eine Feier was kann ich kleiden',
    'Am Wochenende besuche ich eine Feier was kann ich tragen',
    'Am Wochenende besuche ich eine Feier was kann ich umbinden',
    'Am Wochenende besuche ich eine Feier was kann ich umhängen',
    'Am Wochenende besuche ich eine Feier was kann ich überstreifen',
    'Am Wochenende besuche ich eine Feier was kann ich überwerfen',
    'Am Wochenende besuche ich eine Feier was kann ich überziehen',
    'Am Wochenende besuche ich eine Feier was könnte ich anlegen',
    'Am Wochenende besuche ich eine Feier was könnte ich anziehen',
    'Am Wochenende besuche ich eine Feier was könnte ich kleiden',
    'Am Wochenende besuche ich eine Feier was könnte ich tragen',
    'Am Wochenende besuche ich eine Feier was könnte ich umbinden',
    'Am Wochenende besuche ich eine Feier was könnte ich umhängen',
    'Am Wochenende besuche ich eine Feier was könnte ich überstreifen',
    'Am Wochenende besuche ich eine Feier was könnte ich überwerfen',
    'Am Wochenende besuche ich eine Feier was könnte ich überziehen',
    'Am Wochenende besuche ich eine Feier was muss ich anlegen',
    'Am Wochenende besuche ich eine Feier was muss ich anziehen',
    'Am Wochenende besuche ich eine Feier was muss ich kleiden',
    'Am Wochenende besuche ich eine Feier was muss ich tragen',
    'Am Wochenende besuche ich eine Feier was muss ich umbinden',
    'Am Wochenende besuche ich eine Feier was muss ich umhängen',
    'Am Wochenende besuche ich eine Feier was muss ich überstreifen',
    'Am Wochenende besuche ich eine Feier was muss ich überwerfen',
    'Am Wochenende besuche ich eine Feier was muss ich überziehen',
    'Am Wochenende besuche ich eine Feier was soll ich anlegen',
    'Am Wochenende besuche ich eine Feier was soll ich anziehen',
    'Am Wochenende besuche ich eine Feier was soll ich kleiden',
    'Am Wochenende besuche ich eine Feier was soll ich tragen',
    'Am Wochenende besuche ich eine Feier was soll ich umbinden',
    'Am Wochenende besuche ich eine Feier was soll ich umhängen',
    'Am Wochenende besuche ich eine Feier was soll ich überstreifen',
    'Am Wochenende besuche ich eine Feier was soll ich überwerfen',
    'Am Wochenende besuche ich eine Feier was soll ich überziehen',
    'Am Wochenende besuche ich eine Feier was sollte ich anlegen',
    'Am Wochenende besuche ich eine Feier was sollte ich anziehen',
    'Am Wochenende besuche ich eine Feier was sollte ich kleiden',
    'Am Wochenende besuche ich eine Feier was sollte ich tragen',
    'Am Wochenende besuche ich eine Feier was sollte ich umbinden',
    'Am Wochenende besuche ich eine Feier was sollte ich umhängen',
    'Am Wochenende besuche ich eine Feier was sollte ich überstreifen',
    'Am Wochenende besuche ich eine Feier was sollte ich überwerfen',
    'Am Wochenende besuche ich eine Feier was sollte ich überziehen',
    'Am Wochenende besuche ich eine Party was darf ich anlegen',
    'Am Wochenende besuche ich eine Party was darf ich anziehen',
    'Am Wochenende besuche ich eine Party was darf ich kleiden',
    'Am Wochenende besuche ich eine Party was darf ich tragen',
    'Am Wochenende besuche ich eine Party was darf ich umbinden',
    'Am Wochenende besuche ich eine Party was darf ich umhängen',
    'Am Wochenende besuche ich eine Party was darf ich überstreifen',
    'Am Wochenende besuche ich eine Party was darf ich überwerfen',
    'Am Wochenende besuche ich eine Party was darf ich überziehen',
    'Am Wochenende besuche ich eine Party was kann ich anlegen',
    'Am Wochenende besuche ich eine Party was kann ich anziehen',
    'Am Wochenende besuche ich eine Party was kann ich kleiden',
    'Am Wochenende besuche ich eine Party was kann ich tragen',
    'Am Wochenende besuche ich eine Party was kann ich umbinden',
    'Am Wochenende besuche ich eine Party was kann ich umhängen',
    'Am Wochenende besuche ich eine Party was kann ich überstreifen',
    'Am Wochenende besuche ich eine Party was kann ich überwerfen',
    'Am Wochenende besuche ich eine Party was kann ich überziehen',
    'Am Wochenende besuche ich eine Party was könnte ich anlegen',
    'Am Wochenende besuche ich eine Party was könnte ich anziehen',
    'Am Wochenende besuche ich eine Party was könnte ich kleiden',
    'Am Wochenende besuche ich eine Party was könnte ich tragen',
    'Am Wochenende besuche ich eine Party was könnte ich umbinden',
    'Am Wochenende besuche ich eine Party was könnte ich umhängen',
    'Am Wochenende besuche ich eine Party was könnte ich überstreifen',
    'Am Wochenende besuche ich eine Party was könnte ich überwerfen',
    'Am Wochenende besuche ich eine Party was könnte ich überziehen',
    'Am Wochenende besuche ich eine Party was muss ich anlegen',
    'Am Wochenende besuche ich eine Party was muss ich anziehen',
    'Am Wochenende besuche ich eine Party was muss ich kleiden',
    'Am Wochenende besuche ich eine Party was muss ich tragen',
    'Am Wochenende besuche ich eine Party was muss ich umbinden',
    'Am Wochenende besuche ich eine Party was muss ich umhängen',
    'Am Wochenende besuche ich eine Party was muss ich überstreifen',
    'Am Wochenende besuche ich eine Party was muss ich überwerfen',
    'Am Wochenende besuche ich eine Party was muss ich überziehen',
    'Am Wochenende besuche ich eine Party was soll ich anlegen',
    'Am Wochenende besuche ich eine Party was soll ich anziehen',
    'Am Wochenende besuche ich eine Party was soll ich kleiden',
    'Am Wochenende besuche ich eine Party was soll ich tragen',
    'Am Wochenende besuche ich eine Party was soll ich umbinden',
    'Am Wochenende besuche ich eine Party was soll ich umhängen',
    'Am Wochenende besuche ich eine Party was soll ich überstreifen',
    'Am Wochenende besuche ich eine Party was soll ich überwerfen',
    'Am Wochenende besuche ich eine Party was soll ich überziehen',
    'Am Wochenende besuche ich eine Party was sollte ich anlegen',
    'Am Wochenende besuche ich eine Party was sollte ich anziehen',
    'Am Wochenende besuche ich eine Party was sollte ich kleiden',
    'Am Wochenende besuche ich eine Party was sollte ich tragen',
    'Am Wochenende besuche ich eine Party was sollte ich umbinden',
    'Am Wochenende besuche ich eine Party was sollte ich umhängen',
    'Am Wochenende besuche ich eine Party was sollte ich überstreifen',
    'Am Wochenende besuche ich eine Party was sollte ich überwerfen',
    'Am Wochenende besuche ich eine Party was sollte ich überziehen',
    'Am Wochenende bin ich auf einer Feier was darf ich anlegen',
    'Am Wochenende bin ich auf einer Feier was darf ich anziehen',
    'Am Wochenende bin ich auf einer Feier was darf ich kleiden',
    'Am Wochenende bin ich auf einer Feier was darf ich tragen',
    'Am Wochenende bin ich auf einer Feier was darf ich umbinden',
    'Am Wochenende bin ich auf einer Feier was darf ich umhängen',
    'Am Wochenende bin ich auf einer Feier was darf ich überstreifen',
    'Am Wochenende bin ich auf einer Feier was darf ich überwerfen',
    'Am Wochenende bin ich auf einer Feier was darf ich überziehen',
    'Am Wochenende bin ich auf einer Feier was kann ich anlegen',
    'Am Wochenende bin ich auf einer Feier was kann ich anziehen',
    'Am Wochenende bin ich auf einer Feier was kann ich kleiden',
    'Am Wochenende bin ich auf einer Feier was kann ich tragen',
    'Am Wochenende bin ich auf einer Feier was kann ich umbinden',
    'Am Wochenende bin ich auf einer Feier was kann ich umhängen',
    'Am Wochenende bin ich auf einer Feier was kann ich überstreifen',
    'Am Wochenende bin ich auf einer Feier was kann ich überwerfen',
    'Am Wochenende bin ich auf einer Feier was kann ich überziehen',
    'Am Wochenende bin ich auf einer Feier was könnte ich anlegen',
    'Am Wochenende bin ich auf einer Feier was könnte ich anziehen',
    'Am Wochenende bin ich auf einer Feier was könnte ich kleiden',
    'Am Wochenende bin ich auf einer Feier was könnte ich tragen',
    'Am Wochenende bin ich auf einer Feier was könnte ich umbinden',
    'Am Wochenende bin ich auf einer Feier was könnte ich umhängen',
    'Am Wochenende bin ich auf einer Feier was könnte ich überstreifen',
    'Am Wochenende bin ich auf einer Feier was könnte ich überwerfen',
    'Am Wochenende bin ich auf einer Feier was könnte ich überziehen',
    'Am Wochenende bin ich auf einer Feier was muss ich anlegen',
    'Am Wochenende bin ich auf einer Feier was muss ich anziehen',
    'Am Wochenende bin ich auf einer Feier was muss ich kleiden',
    'Am Wochenende bin ich auf einer Feier was muss ich tragen',
    'Am Wochenende bin ich auf einer Feier was muss ich umbinden',
    'Am Wochenende bin ich auf einer Feier was muss ich umhängen',
    'Am Wochenende bin ich auf einer Feier was muss ich überstreifen',
    'Am Wochenende bin ich auf einer Feier was muss ich überwerfen',
    'Am Wochenende bin ich auf einer Feier was muss ich überziehen',
    'Am Wochenende bin ich auf einer Feier was soll ich anlegen',
    'Am Wochenende bin ich auf einer Feier was soll ich anziehen',
    'Am Wochenende bin ich auf einer Feier was soll ich kleiden',
    'Am Wochenende bin ich auf einer Feier was soll ich tragen',
    'Am Wochenende bin ich auf einer Feier was soll ich umbinden',
    'Am Wochenende bin ich auf einer Feier was soll ich umhängen',
    'Am Wochenende bin ich auf einer Feier was soll ich überstreifen',
    'Am Wochenende bin ich auf einer Feier was soll ich überwerfen',
    'Am Wochenende bin ich auf einer Feier was soll ich überziehen',
    'Am Wochenende bin ich auf einer Feier was sollte ich anlegen',
    'Am Wochenende bin ich auf einer Feier was sollte ich anziehen',
    'Am Wochenende bin ich auf einer Feier was sollte ich kleiden',
    'Am Wochenende bin ich auf einer Feier was sollte ich tragen',
    'Am Wochenende bin ich auf einer Feier was sollte ich umbinden',
    'Am Wochenende bin ich auf einer Feier was sollte ich umhängen',
    'Am Wochenende bin ich auf einer Feier was sollte ich überstreifen',
    'Am Wochenende bin ich auf einer Feier was sollte ich überwerfen',
    'Am Wochenende bin ich auf einer Feier was sollte ich überziehen',
    'Am Wochenende bin ich auf einer Party was darf ich anlegen',
    'Am Wochenende bin ich auf einer Party was darf ich anziehen',
    'Am Wochenende bin ich auf einer Party was darf ich kleiden',
    'Am Wochenende bin ich auf einer Party was darf ich tragen',
    'Am Wochenende bin ich auf einer Party was darf ich umbinden',
    'Am Wochenende bin ich auf einer Party was darf ich umhängen',
    'Am Wochenende bin ich auf einer Party was darf ich überstreifen',
    'Am Wochenende bin ich auf einer Party was darf ich überwerfen',
    'Am Wochenende bin ich auf einer Party was darf ich überziehen',
    'Am Wochenende bin ich auf einer Party was kann ich anlegen',
    'Am Wochenende bin ich auf einer Party was kann ich anziehen',
    'Am Wochenende bin ich auf einer Party was kann ich kleiden',
    'Am Wochenende bin ich auf einer Party was kann ich tragen',
    'Am Wochenende bin ich auf einer Party was kann ich umbinden',
    'Am Wochenende bin ich auf einer Party was kann ich umhängen',
    'Am Wochenende bin ich auf einer Party was kann ich überstreifen',
    'Am Wochenende bin ich auf einer Party was kann ich überwerfen',
    'Am Wochenende bin ich auf einer Party was kann ich überziehen',
    'Am Wochenende bin ich auf einer Party was könnte ich anlegen',
    'Am Wochenende bin ich auf einer Party was könnte ich anziehen',
    'Am Wochenende bin ich auf einer Party was könnte ich kleiden',
    'Am Wochenende bin ich auf einer Party was könnte ich tragen',
    'Am Wochenende bin ich auf einer Party was könnte ich umbinden',
    'Am Wochenende bin ich auf einer Party was könnte ich umhängen',
    'Am Wochenende bin ich auf einer Party was könnte ich überstreifen',
    'Am Wochenende bin ich auf einer Party was könnte ich überwerfen',
    'Am Wochenende bin ich auf einer Party was könnte ich überziehen',
    'Am Wochenende bin ich auf einer Party was muss ich anlegen',
    'Am Wochenende bin ich auf einer Party was muss ich anziehen',
    'Am Wochenende bin ich auf einer Party was muss ich kleiden',
    'Am Wochenende bin ich auf einer Party was muss ich tragen',
    'Am Wochenende bin ich auf einer Party was muss ich umbinden',
    'Am Wochenende bin ich auf einer Party was muss ich umhängen',
    'Am Wochenende bin ich auf einer Party was muss ich überstreifen',
    'Am Wochenende bin ich auf einer Party was muss ich überwerfen',
    'Am Wochenende bin ich auf einer Party was muss ich überziehen',
    'Am Wochenende bin ich auf einer Party was soll ich anlegen',
    'Am Wochenende bin ich auf einer Party was soll ich anziehen',
    'Am Wochenende bin ich auf einer Party was soll ich kleiden',
    'Am Wochenende bin ich auf einer Party was soll ich tragen',
    'Am Wochenende bin ich auf einer Party was soll ich umbinden',
    'Am Wochenende bin ich auf einer Party was soll ich umhängen',
    'Am Wochenende bin ich auf einer Party was soll ich überstreifen',
    'Am Wochenende bin ich auf einer Party was soll ich überwerfen',
    'Am Wochenende bin ich auf einer Party was soll ich überziehen',
    'Am Wochenende bin ich auf einer Party was sollte ich anlegen',
    'Am Wochenende bin ich auf einer Party was sollte ich anziehen',
    'Am Wochenende bin ich auf einer Party was sollte ich kleiden',
    'Am Wochenende bin ich auf einer Party was sollte ich tragen',
    'Am Wochenende bin ich auf einer Party was sollte ich umbinden',
    'Am Wochenende bin ich auf einer Party was sollte ich umhängen',
    'Am Wochenende bin ich auf einer Party was sollte ich überstreifen',
    'Am Wochenende bin ich auf einer Party was sollte ich überwerfen',
    'Am Wochenende bin ich auf einer Party was sollte ich überziehen',
    'Was darf ich anlegen',
    'Was darf ich anziehen',
    'Was darf ich kleiden',
    'Was darf ich tragen',
    'Was darf ich umbinden',
    'Was darf ich umhängen',
    'Was darf ich überstreifen',
    'Was darf ich überwerfen',
    'Was darf ich überziehen',
    'Was kann ich anlegen',
    'Was kann ich anziehen',
    'Was kann ich kleiden',
    'Was kann ich tragen',
    'Was kann ich umbinden',
    'Was kann ich umhängen',
    'Was kann ich überstreifen',
    'Was kann ich überwerfen',
    'Was kann ich überziehen',
    'Was könnte ich anlegen',
    'Was könnte ich anziehen',
    'Was könnte ich kleiden',
    'Was könnte ich tragen',
    'Was könnte ich umbinden',
    'Was könnte ich umhängen',
    'Was könnte ich überstreifen',
    'Was könnte ich überwerfen',
    'Was könnte ich überziehen',
    'Was muss ich anlegen',
    'Was muss ich anziehen',
    'Was muss ich kleiden',
    'Was muss ich tragen',
    'Was muss ich umbinden',
    'Was muss ich umhängen',
    'Was muss ich überstreifen',
    'Was muss ich überwerfen',
    'Was muss ich überziehen',
    'Was soll ich anlegen',
    'Was soll ich anziehen',
    'Was soll ich kleiden',
    'Was soll ich tragen',
    'Was soll ich umbinden',
    'Was soll ich umhängen',
    'Was soll ich überstreifen',
    'Was soll ich überwerfen',
    'Was soll ich überziehen',
    'Was sollte ich anlegen',
    'Was sollte ich anziehen',
    'Was sollte ich kleiden',
    'Was sollte ich tragen',
    'Was sollte ich umbinden',
    'Was sollte ich umhängen',
    'Was sollte ich überstreifen',
    'Was sollte ich überwerfen',
    'Was sollte ich überziehen',
  ]
};
