export default {
  slots: {},
  utterances: [
    'Bekomme ich das auch in Größe Achtunddreißig',
    'Bekomme ich das auch in einer anderen Größe',
    'Bekomme ich den auch in Größe Achtunddreißig',
    'Bekomme ich den auch in einer anderen Größe',
    'Das passt leider nicht Bekomme ich das auch in Größe Achtunddreißig',
    'Das passt leider nicht Bekomme ich das auch in einer anderen Größe',
    'Das passt leider nicht Bekomme ich den auch in Größe Achtunddreißig',
    'Das passt leider nicht Bekomme ich den auch in einer anderen Größe',
    'Das passt leider nicht Gibt es das auch in Größe Achtunddreißig',
    'Das passt leider nicht Gibt es das auch in einer anderen Größe',
    'Das passt leider nicht Gibt es den auch in Größe Achtunddreißig',
    'Das passt leider nicht Gibt es den auch in einer anderen Größe',
    'Das passt leider nicht Kriege ich das auch in Größe Achtunddreißig',
    'Das passt leider nicht Kriege ich das auch in einer anderen Größe',
    'Das passt leider nicht Kriege ich den auch in Größe Achtunddreißig',
    'Das passt leider nicht Kriege ich den auch in einer anderen Größe',
    'Das passt nicht Bekomme ich das auch in Größe Achtunddreißig',
    'Das passt nicht Bekomme ich das auch in einer anderen Größe',
    'Das passt nicht Bekomme ich den auch in Größe Achtunddreißig',
    'Das passt nicht Bekomme ich den auch in einer anderen Größe',
    'Das passt nicht Gibt es das auch in Größe Achtunddreißig',
    'Das passt nicht Gibt es das auch in einer anderen Größe',
    'Das passt nicht Gibt es den auch in Größe Achtunddreißig',
    'Das passt nicht Gibt es den auch in einer anderen Größe',
    'Das passt nicht Kriege ich das auch in Größe Achtunddreißig',
    'Das passt nicht Kriege ich das auch in einer anderen Größe',
    'Das passt nicht Kriege ich den auch in Größe Achtunddreißig',
    'Das passt nicht Kriege ich den auch in einer anderen Größe',
    'Das sitzt leider nicht Bekomme ich das auch in Größe Achtunddreißig',
    'Das sitzt leider nicht Bekomme ich das auch in einer anderen Größe',
    'Das sitzt leider nicht Bekomme ich den auch in Größe Achtunddreißig',
    'Das sitzt leider nicht Bekomme ich den auch in einer anderen Größe',
    'Das sitzt leider nicht Gibt es das auch in Größe Achtunddreißig',
    'Das sitzt leider nicht Gibt es das auch in einer anderen Größe',
    'Das sitzt leider nicht Gibt es den auch in Größe Achtunddreißig',
    'Das sitzt leider nicht Gibt es den auch in einer anderen Größe',
    'Das sitzt leider nicht Kriege ich das auch in Größe Achtunddreißig',
    'Das sitzt leider nicht Kriege ich das auch in einer anderen Größe',
    'Das sitzt leider nicht Kriege ich den auch in Größe Achtunddreißig',
    'Das sitzt leider nicht Kriege ich den auch in einer anderen Größe',
    'Das sitzt nicht Bekomme ich das auch in Größe Achtunddreißig',
    'Das sitzt nicht Bekomme ich das auch in einer anderen Größe',
    'Das sitzt nicht Bekomme ich den auch in Größe Achtunddreißig',
    'Das sitzt nicht Bekomme ich den auch in einer anderen Größe',
    'Das sitzt nicht Gibt es das auch in Größe Achtunddreißig',
    'Das sitzt nicht Gibt es das auch in einer anderen Größe',
    'Das sitzt nicht Gibt es den auch in Größe Achtunddreißig',
    'Das sitzt nicht Gibt es den auch in einer anderen Größe',
    'Das sitzt nicht Kriege ich das auch in Größe Achtunddreißig',
    'Das sitzt nicht Kriege ich das auch in einer anderen Größe',
    'Das sitzt nicht Kriege ich den auch in Größe Achtunddreißig',
    'Das sitzt nicht Kriege ich den auch in einer anderen Größe',
    'Der Anzug passt leider nicht Bekomme ich das auch in Größe Achtunddreißig',
    'Der Anzug passt leider nicht Bekomme ich das auch in einer anderen Größe',
    'Der Anzug passt leider nicht Bekomme ich den auch in Größe Achtunddreißig',
    'Der Anzug passt leider nicht Bekomme ich den auch in einer anderen Größe',
    'Der Anzug passt leider nicht Gibt es das auch in Größe Achtunddreißig',
    'Der Anzug passt leider nicht Gibt es das auch in einer anderen Größe',
    'Der Anzug passt leider nicht Gibt es den auch in Größe Achtunddreißig',
    'Der Anzug passt leider nicht Gibt es den auch in einer anderen Größe',
    'Der Anzug passt leider nicht Kriege ich das auch in Größe Achtunddreißig',
    'Der Anzug passt leider nicht Kriege ich das auch in einer anderen Größe',
    'Der Anzug passt leider nicht Kriege ich den auch in Größe Achtunddreißig',
    'Der Anzug passt leider nicht Kriege ich den auch in einer anderen Größe',
    'Der Anzug passt nicht Bekomme ich das auch in Größe Achtunddreißig',
    'Der Anzug passt nicht Bekomme ich das auch in einer anderen Größe',
    'Der Anzug passt nicht Bekomme ich den auch in Größe Achtunddreißig',
    'Der Anzug passt nicht Bekomme ich den auch in einer anderen Größe',
    'Der Anzug passt nicht Gibt es das auch in Größe Achtunddreißig',
    'Der Anzug passt nicht Gibt es das auch in einer anderen Größe',
    'Der Anzug passt nicht Gibt es den auch in Größe Achtunddreißig',
    'Der Anzug passt nicht Gibt es den auch in einer anderen Größe',
    'Der Anzug passt nicht Kriege ich das auch in Größe Achtunddreißig',
    'Der Anzug passt nicht Kriege ich das auch in einer anderen Größe',
    'Der Anzug passt nicht Kriege ich den auch in Größe Achtunddreißig',
    'Der Anzug passt nicht Kriege ich den auch in einer anderen Größe',
    'Der Anzug sitzt leider nicht Bekomme ich das auch in Größe Achtunddreißig',
    'Der Anzug sitzt leider nicht Bekomme ich das auch in einer anderen Größe',
    'Der Anzug sitzt leider nicht Bekomme ich den auch in Größe Achtunddreißig',
    'Der Anzug sitzt leider nicht Bekomme ich den auch in einer anderen Größe',
    'Der Anzug sitzt leider nicht Gibt es das auch in Größe Achtunddreißig',
    'Der Anzug sitzt leider nicht Gibt es das auch in einer anderen Größe',
    'Der Anzug sitzt leider nicht Gibt es den auch in Größe Achtunddreißig',
    'Der Anzug sitzt leider nicht Gibt es den auch in einer anderen Größe',
    'Der Anzug sitzt leider nicht Kriege ich das auch in Größe Achtunddreißig',
    'Der Anzug sitzt leider nicht Kriege ich das auch in einer anderen Größe',
    'Der Anzug sitzt leider nicht Kriege ich den auch in Größe Achtunddreißig',
    'Der Anzug sitzt leider nicht Kriege ich den auch in einer anderen Größe',
    'Der Anzug sitzt nicht Bekomme ich das auch in Größe Achtunddreißig',
    'Der Anzug sitzt nicht Bekomme ich das auch in einer anderen Größe',
    'Der Anzug sitzt nicht Bekomme ich den auch in Größe Achtunddreißig',
    'Der Anzug sitzt nicht Bekomme ich den auch in einer anderen Größe',
    'Der Anzug sitzt nicht Gibt es das auch in Größe Achtunddreißig',
    'Der Anzug sitzt nicht Gibt es das auch in einer anderen Größe',
    'Der Anzug sitzt nicht Gibt es den auch in Größe Achtunddreißig',
    'Der Anzug sitzt nicht Gibt es den auch in einer anderen Größe',
    'Der Anzug sitzt nicht Kriege ich das auch in Größe Achtunddreißig',
    'Der Anzug sitzt nicht Kriege ich das auch in einer anderen Größe',
    'Der Anzug sitzt nicht Kriege ich den auch in Größe Achtunddreißig',
    'Der Anzug sitzt nicht Kriege ich den auch in einer anderen Größe',
    'Der Artikel passt leider nicht Bekomme ich das auch in Größe Achtunddreißig',
    'Der Artikel passt leider nicht Bekomme ich das auch in einer anderen Größe',
    'Der Artikel passt leider nicht Bekomme ich den auch in Größe Achtunddreißig',
    'Der Artikel passt leider nicht Bekomme ich den auch in einer anderen Größe',
    'Der Artikel passt leider nicht Gibt es das auch in Größe Achtunddreißig',
    'Der Artikel passt leider nicht Gibt es das auch in einer anderen Größe',
    'Der Artikel passt leider nicht Gibt es den auch in Größe Achtunddreißig',
    'Der Artikel passt leider nicht Gibt es den auch in einer anderen Größe',
    'Der Artikel passt leider nicht Kriege ich das auch in Größe Achtunddreißig',
    'Der Artikel passt leider nicht Kriege ich das auch in einer anderen Größe',
    'Der Artikel passt leider nicht Kriege ich den auch in Größe Achtunddreißig',
    'Der Artikel passt leider nicht Kriege ich den auch in einer anderen Größe',
    'Der Artikel passt nicht Bekomme ich das auch in Größe Achtunddreißig',
    'Der Artikel passt nicht Bekomme ich das auch in einer anderen Größe',
    'Der Artikel passt nicht Bekomme ich den auch in Größe Achtunddreißig',
    'Der Artikel passt nicht Bekomme ich den auch in einer anderen Größe',
    'Der Artikel passt nicht Gibt es das auch in Größe Achtunddreißig',
    'Der Artikel passt nicht Gibt es das auch in einer anderen Größe',
    'Der Artikel passt nicht Gibt es den auch in Größe Achtunddreißig',
    'Der Artikel passt nicht Gibt es den auch in einer anderen Größe',
    'Der Artikel passt nicht Kriege ich das auch in Größe Achtunddreißig',
    'Der Artikel passt nicht Kriege ich das auch in einer anderen Größe',
    'Der Artikel passt nicht Kriege ich den auch in Größe Achtunddreißig',
    'Der Artikel passt nicht Kriege ich den auch in einer anderen Größe',
    'Der Artikel sitzt leider nicht Bekomme ich das auch in Größe Achtunddreißig',
    'Der Artikel sitzt leider nicht Bekomme ich das auch in einer anderen Größe',
    'Der Artikel sitzt leider nicht Bekomme ich den auch in Größe Achtunddreißig',
    'Der Artikel sitzt leider nicht Bekomme ich den auch in einer anderen Größe',
    'Der Artikel sitzt leider nicht Gibt es das auch in Größe Achtunddreißig',
    'Der Artikel sitzt leider nicht Gibt es das auch in einer anderen Größe',
    'Der Artikel sitzt leider nicht Gibt es den auch in Größe Achtunddreißig',
    'Der Artikel sitzt leider nicht Gibt es den auch in einer anderen Größe',
    'Der Artikel sitzt leider nicht Kriege ich das auch in Größe Achtunddreißig',
    'Der Artikel sitzt leider nicht Kriege ich das auch in einer anderen Größe',
    'Der Artikel sitzt leider nicht Kriege ich den auch in Größe Achtunddreißig',
    'Der Artikel sitzt leider nicht Kriege ich den auch in einer anderen Größe',
    'Der Artikel sitzt nicht Bekomme ich das auch in Größe Achtunddreißig',
    'Der Artikel sitzt nicht Bekomme ich das auch in einer anderen Größe',
    'Der Artikel sitzt nicht Bekomme ich den auch in Größe Achtunddreißig',
    'Der Artikel sitzt nicht Bekomme ich den auch in einer anderen Größe',
    'Der Artikel sitzt nicht Gibt es das auch in Größe Achtunddreißig',
    'Der Artikel sitzt nicht Gibt es das auch in einer anderen Größe',
    'Der Artikel sitzt nicht Gibt es den auch in Größe Achtunddreißig',
    'Der Artikel sitzt nicht Gibt es den auch in einer anderen Größe',
    'Der Artikel sitzt nicht Kriege ich das auch in Größe Achtunddreißig',
    'Der Artikel sitzt nicht Kriege ich das auch in einer anderen Größe',
    'Der Artikel sitzt nicht Kriege ich den auch in Größe Achtunddreißig',
    'Der Artikel sitzt nicht Kriege ich den auch in einer anderen Größe',
    'Der Blazer passt leider nicht Bekomme ich das auch in Größe Achtunddreißig',
    'Der Blazer passt leider nicht Bekomme ich das auch in einer anderen Größe',
    'Der Blazer passt leider nicht Bekomme ich den auch in Größe Achtunddreißig',
    'Der Blazer passt leider nicht Bekomme ich den auch in einer anderen Größe',
    'Der Blazer passt leider nicht Gibt es das auch in Größe Achtunddreißig',
    'Der Blazer passt leider nicht Gibt es das auch in einer anderen Größe',
    'Der Blazer passt leider nicht Gibt es den auch in Größe Achtunddreißig',
    'Der Blazer passt leider nicht Gibt es den auch in einer anderen Größe',
    'Der Blazer passt leider nicht Kriege ich das auch in Größe Achtunddreißig',
    'Der Blazer passt leider nicht Kriege ich das auch in einer anderen Größe',
    'Der Blazer passt leider nicht Kriege ich den auch in Größe Achtunddreißig',
    'Der Blazer passt leider nicht Kriege ich den auch in einer anderen Größe',
    'Der Blazer passt nicht Bekomme ich das auch in Größe Achtunddreißig',
    'Der Blazer passt nicht Bekomme ich das auch in einer anderen Größe',
    'Der Blazer passt nicht Bekomme ich den auch in Größe Achtunddreißig',
    'Der Blazer passt nicht Bekomme ich den auch in einer anderen Größe',
    'Der Blazer passt nicht Gibt es das auch in Größe Achtunddreißig',
    'Der Blazer passt nicht Gibt es das auch in einer anderen Größe',
    'Der Blazer passt nicht Gibt es den auch in Größe Achtunddreißig',
    'Der Blazer passt nicht Gibt es den auch in einer anderen Größe',
    'Der Blazer passt nicht Kriege ich das auch in Größe Achtunddreißig',
    'Der Blazer passt nicht Kriege ich das auch in einer anderen Größe',
    'Der Blazer passt nicht Kriege ich den auch in Größe Achtunddreißig',
    'Der Blazer passt nicht Kriege ich den auch in einer anderen Größe',
    'Der Blazer sitzt leider nicht Bekomme ich das auch in Größe Achtunddreißig',
    'Der Blazer sitzt leider nicht Bekomme ich das auch in einer anderen Größe',
    'Der Blazer sitzt leider nicht Bekomme ich den auch in Größe Achtunddreißig',
    'Der Blazer sitzt leider nicht Bekomme ich den auch in einer anderen Größe',
    'Der Blazer sitzt leider nicht Gibt es das auch in Größe Achtunddreißig',
    'Der Blazer sitzt leider nicht Gibt es das auch in einer anderen Größe',
    'Der Blazer sitzt leider nicht Gibt es den auch in Größe Achtunddreißig',
    'Der Blazer sitzt leider nicht Gibt es den auch in einer anderen Größe',
    'Der Blazer sitzt leider nicht Kriege ich das auch in Größe Achtunddreißig',
    'Der Blazer sitzt leider nicht Kriege ich das auch in einer anderen Größe',
    'Der Blazer sitzt leider nicht Kriege ich den auch in Größe Achtunddreißig',
    'Der Blazer sitzt leider nicht Kriege ich den auch in einer anderen Größe',
    'Der Blazer sitzt nicht Bekomme ich das auch in Größe Achtunddreißig',
    'Der Blazer sitzt nicht Bekomme ich das auch in einer anderen Größe',
    'Der Blazer sitzt nicht Bekomme ich den auch in Größe Achtunddreißig',
    'Der Blazer sitzt nicht Bekomme ich den auch in einer anderen Größe',
    'Der Blazer sitzt nicht Gibt es das auch in Größe Achtunddreißig',
    'Der Blazer sitzt nicht Gibt es das auch in einer anderen Größe',
    'Der Blazer sitzt nicht Gibt es den auch in Größe Achtunddreißig',
    'Der Blazer sitzt nicht Gibt es den auch in einer anderen Größe',
    'Der Blazer sitzt nicht Kriege ich das auch in Größe Achtunddreißig',
    'Der Blazer sitzt nicht Kriege ich das auch in einer anderen Größe',
    'Der Blazer sitzt nicht Kriege ich den auch in Größe Achtunddreißig',
    'Der Blazer sitzt nicht Kriege ich den auch in einer anderen Größe',
    'Gibt es das auch in Größe Achtunddreißig',
    'Gibt es das auch in einer anderen Größe',
    'Gibt es den auch in Größe Achtunddreißig',
    'Gibt es den auch in einer anderen Größe',
    'Kriege ich das auch in Größe Achtunddreißig',
    'Kriege ich das auch in einer anderen Größe',
    'Kriege ich den auch in Größe Achtunddreißig',
    'Kriege ich den auch in einer anderen Größe',
  ]
};
