import {request, RequestHandler, response} from 'alexa-app';
import {Ssml} from 'ssml-gib';

const locations = {
  'wohnen': `im vierten Obergeschoss`,
  'bettwäsche': `im vierten Obergeschoss`,
  'bettwasche': `im vierten Obergeschoss`,
  'frottierware': `im vierten Obergeschoss`,
  'küchenartikel': `im vierten Obergeschoss`,
  'kuchenartikel': `im vierten Obergeschoss`,
  'porzellan': `im vierten Obergeschoss`,
  'papeterie': `im vierten Obergeschoss`,
  'reisegepäck': `im vierten Obergeschoss`,
  'reisegepack': `im vierten Obergeschoss`,
  'restaurant karls kitchen': `im vierten Obergeschoss`,
  'karls kitchen': `im vierten Obergeschoss`,
  'karls': `im vierten Obergeschoss`,
  'frisuer': `im vierten Obergeschoss`,
  'die friseure': `im vierten Obergeschoss`,
  'friseure': `im vierten Obergeschoss`,
  'kundenservice': `im vierten Obergeschoss`,
  'click und collect': `im vierten Obergeschoss`,
  'hochzeitsservice': `im vierten Obergeschoss`,
  'hochzeits-service': `im vierten Obergeschoss`,
  'geschenkverpackung': `im vierten Obergeschoss`,
  'sammelkasse': `im vierten Obergeschoss`,
  'kundengarderobe': `im vierten Obergeschoss`,
  'garderobe': `im vierten Obergeschoss`,
  'garderoben': `im vierten Obergeschoss`,
  'kundentoilette': `im vierten Obergeschoss`,
  'kundentoiletten': `im vierten Obergeschoss`,
  'toilette': `im vierten Obergeschoss`,
  'toiletten': `im vierten Obergeschoss`,
  'wickelraum': `im vierten und ersten Obergeschoss sowie im Untergeschoss`,
  'wickel raum': `im vierten und ersten Obergeschoss sowie im Untergeschoss`,
  'wickelräume': `im vierten und ersten Obergeschoss sowie im Untergeschoss`,
  'wickel räume': `im vierten und ersten Obergeschoss sowie im Untergeschoss`,

  'sport': `im dritten Obergeschoss`,
  'abendmode': `im dritten Obergeschoss`,
  'jacken': `im dritten Obergeschoss`,
  'mäntel': `im dritten Obergeschoss`,
  'mantel': `im dritten Obergeschoss`,
  'trachtenmode': `im dritten Obergeschoss`,
  'subway': `im dritten Obergeschoss`,
  'young fashion': `im dritten Obergeschoss`,
  'trend sneaker': `im dritten Obergeschoss`,
  'reisebüro': `im dritten Obergeschoss`,
  'reiseburo': `im dritten Obergeschoss`,
  'ticket center': `im dritten Obergeschoss`,
  'sportwerkstatt': `im dritten Obergeschoss`,
  'kinderzimmer': `im dritten Obergeschoss`,

  'herren': `im zweiten Obergeschoss`,
  'herren premium designer': `im zweiten Obergeschoss`,
  'herren designer': `im zweiten Obergeschoss`,
  'herren premium': `im zweiten Obergeschoss`,
  'herren exquisit': `im zweiten Obergeschoss`,
  'anzüge': `im zweiten Obergeschoss`,
  'hemden': `im zweiten Obergeschoss`,
  'herren hosen': `im zweiten Obergeschoss`,
  'hosen': `Herrenhosen im zweiten Obergeschoss, Damenhosen im ersten Obergeschoss und im Erdgeschoss`,
  'jeans': `im zweiten Obergeschoss`,
  'made to measure': `im zweiten Obergeschoss`,
  'sakkos': `im zweiten Obergeschoss`,
  'herren schuhe': `im zweiten Obergeschoss`,
  'herrenschuhe': `im zweiten Obergeschoss`,
  'schuhe': `Herrenschuhe im zweiten Obergeschoss, Damenschuhe im Untergeschoss`,
  'sportswear': `im zweiten Obergeschoss`,
  'oberteile': `im zweiten Obergeschoss`,
  'änderungsatelier': `im zweiten Obergeschoss`,
  'anderungsatelier': `im zweiten Obergeschoss`,
  'änderungsschneiderei': `im zweiten Obergeschoss`,
  'anderungsschneiderei': `im zweiten Obergeschoss`,
  'atelier': `im zweiten Obergeschoss`,
  'schneiderei': `im zweiten Obergeschoss`,
  'special service': `im zweiten Obergeschoss`,
  'special': `im zweiten Obergeschoss`,
  'gents bar cafe': `im zweiten Obergeschoss`,

  'damen': `im ersten Obergeschoss`,
  'damen premium designer': `im ersten Obergeschoss`,
  'damen designer': `im ersten Obergeschoss`,
  'damen premium': `im ersten Obergeschoss`,
  'damen equisit': `im ersten Obergeschoss`,
  'classic woman': `im ersten Obergeschoss`,
  'modern woman': `im ersten Obergeschoss`,
  'woman': `im ersten Obergeschoss`,
  'blusen': `im ersten Obergeschoss und im Erdgeschoss`,
  'damen hosen': `im ersten Obergeschoss und im Erdgeschoss`,
  'sonnenbrillen': `im ersten Obergeschoss`,
  'accessoires': `im ersten Obergeschoss`,
  'schmuck': `im ersten Obergeschoss`,
  'uhren': `im ersten Obergeschoss`,
  'lauder': `im ersten Obergeschoss`,
  'one m cafe': `im ersten Obergeschoss`,
  'tiffany': `im ersten Obergeschoss`,
  'cartier': `im ersten Obergeschoss`,
  'iwc': `im ersten Obergeschoss`,
  'omega': `im ersten Obergeschoss`,
  'glashütte original': `im ersten Obergeschoss`,
  'glashutte original': `im ersten Obergeschoss`,
  'glashütte': `im ersten Obergeschoss`,
  'glashutte': `im ersten Obergeschoss`,
  'lumas shop': `im ersten Obergeschoss`,
  'lumas': `im ersten Obergeschoss`,
  'ray ban': `im ersten Obergeschoss`,

  'premium designer accessoires': `im Erdgeschoss`,
  'beauty welt': `im Erdgeschoss`,
  'beauty': `im Erdgeschoss`,
  'strick': `im Erdgeschoss`,
  'sansibar': `im Erdgeschoss`,
  'restaurant sansibar': `im Erdgeschoss`,
  'restaurant': `im Erdgeschoss`,
  'karlspassage': `im Erdgeschoss`,
  'passage': `im Erdgeschoss`,
  'confiserie': `im Erdgeschoss`,
  'konfiserie': `im Erdgeschoss`,
  'dieconfiserie': `im Erdgeschoss`,
  'diekonfiserie': `im Erdgeschoss`,
  'die confiserie': `im Erdgeschoss`,
  'die konfiserie': `im Erdgeschoss`,
  'breuninger confiserie': `im Erdgeschoss`,
  'breuninger konfiserie': `im Erdgeschoss`,
  'aesop store': `im Erdgeschoss`,
  'aesop': `im Erdgeschoss`,
  'lakrids store': `im Erdgeschoss`,
  'lakrids': `im Erdgeschoss`,
  'hackett shop': `im Erdgeschoss`,
  'hackett': `im Erdgeschoss`,
  'shiseido beauty lounge': `im Erdgeschoss`,
  'shiseido': `im Erdgeschoss`,
  'dürninger presse': `im Erdgeschoss`,
  'durninger presse': `im Erdgeschoss`,
  'presse': `im Erdgeschoss`,
  'dürninger tabak': `im Erdgeschoss`,
  'durninger tabak': `im Erdgeschoss`,
  'tabak': `im Erdgeschoss`,
  'mann blumen und deko': `im Erdgeschoss`,
  'blumen und deko': `im Erdgeschoss`,
  'blumen': `im Erdgeschoss`,
  'deko': `im Erdgeschoss`,
  'gravis apple store': `im Erdgeschoss`,
  'apple store': `im Erdgeschoss`,
  'apple': `im Erdgeschoss`,
  'gravis store': `im Erdgeschoss`,
  'gravis': `im Erdgeschoss`,

  'damen schuhe': `im Untergeschoss`,
  'damenschuhe': `im Untergeschoss`,
  'kinder': `im Untergeschoss`,
  'wäsche': `im Untergeschoss`,
  'wasche': `im Untergeschoss`,
  'strümpfe': `im Untergeschoss`,
  'strumpfe': `im Untergeschoss`,
  'candy und company': `im Untergeschoss`,
  'candy': `im Untergeschoss`,
  'süßigkeiten': `im Untergeschoss`,
  'sußigkeiten': `im Untergeschoss`,
  'kinderfriseur': `im Untergeschoss`,
  'kinderfriseure': `im Untergeschoss`,
  'heels salon cafe bar': `im Untergeschoss`,
  'heels salon bar': `im Untergeschoss`,
  'heels bar': `im Untergeschoss`,
  'heels salon cafe': `im Untergeschoss`,
  'heels salon': `im Untergeschoss`
};

function NavigationIntentHandler(this: RequestHandler, alexaRequest: request, alexaResponse: response): void {
  const location = locations[alexaRequest.slot('query').toLowerCase()];
  if (location == undefined) {
    alexaResponse.say(`Leider können wir Ihnen derzeit keine Auskunft zum Ort von ${alexaRequest.slot(
      'query')} geben, bitte wenden Sie sich an einen ${Ssml.prosody('Breuninger', {rate: 110})} Mitarbeiter.`)
      .reprompt('Versuchen Sie einen anderen Begriff.')
      .shouldEndSession(false);
  } else {
    alexaResponse.say(`Sie können ${alexaRequest.slot('query')} ${location} finden!`)
      .reprompt('Brauchen Sie eine genaue Wegbeschreibung?')
      .shouldEndSession(false);

  }
}

export default NavigationIntentHandler;
