export default {
  slots: {},
  utterances: [
    'Darf ich das anprobieren',
    'Darf ich das auch anprobieren',
    'Darf ich das auch ausprobieren',
    'Darf ich das auch testen',
    'Darf ich das ausprobieren',
    'Darf ich das mal anprobieren',
    'Darf ich das mal ausprobieren',
    'Darf ich das mal testen',
    'Darf ich das testen',
    'Darf ich den anprobieren',
    'Darf ich den auch anprobieren',
    'Darf ich den auch ausprobieren',
    'Darf ich den auch testen',
    'Darf ich den ausprobieren',
    'Darf ich den mal anprobieren',
    'Darf ich den mal ausprobieren',
    'Darf ich den mal testen',
    'Darf ich den testen',
    'Darf ich die anprobieren',
    'Darf ich die auch anprobieren',
    'Darf ich die auch ausprobieren',
    'Darf ich die auch testen',
    'Darf ich die ausprobieren',
    'Darf ich die mal anprobieren',
    'Darf ich die mal ausprobieren',
    'Darf ich die mal testen',
    'Darf ich die testen',
    'Kann ich das anprobieren',
    'Kann ich das auch anprobieren',
    'Kann ich das auch ausprobieren',
    'Kann ich das auch testen',
    'Kann ich das ausprobieren',
    'Kann ich das mal anprobieren',
    'Kann ich das mal ausprobieren',
    'Kann ich das mal testen',
    'Kann ich das testen',
    'Kann ich den anprobieren',
    'Kann ich den auch anprobieren',
    'Kann ich den auch ausprobieren',
    'Kann ich den auch testen',
    'Kann ich den ausprobieren',
    'Kann ich den mal anprobieren',
    'Kann ich den mal ausprobieren',
    'Kann ich den mal testen',
    'Kann ich den testen',
    'Kann ich die anprobieren',
    'Kann ich die auch anprobieren',
    'Kann ich die auch ausprobieren',
    'Kann ich die auch testen',
    'Kann ich die ausprobieren',
    'Kann ich die mal anprobieren',
    'Kann ich die mal ausprobieren',
    'Kann ich die mal testen',
    'Kann ich die testen',
    'Toll darf ich das anprobieren',
    'Toll darf ich das auch anprobieren',
    'Toll darf ich das auch ausprobieren',
    'Toll darf ich das auch testen',
    'Toll darf ich das ausprobieren',
    'Toll darf ich das mal anprobieren',
    'Toll darf ich das mal ausprobieren',
    'Toll darf ich das mal testen',
    'Toll darf ich das testen',
    'Toll darf ich den anprobieren',
    'Toll darf ich den auch anprobieren',
    'Toll darf ich den auch ausprobieren',
    'Toll darf ich den auch testen',
    'Toll darf ich den ausprobieren',
    'Toll darf ich den mal anprobieren',
    'Toll darf ich den mal ausprobieren',
    'Toll darf ich den mal testen',
    'Toll darf ich den testen',
    'Toll darf ich die anprobieren',
    'Toll darf ich die auch anprobieren',
    'Toll darf ich die auch ausprobieren',
    'Toll darf ich die auch testen',
    'Toll darf ich die ausprobieren',
    'Toll darf ich die mal anprobieren',
    'Toll darf ich die mal ausprobieren',
    'Toll darf ich die mal testen',
    'Toll darf ich die testen',
    'Toll kann ich das anprobieren',
    'Toll kann ich das auch anprobieren',
    'Toll kann ich das auch ausprobieren',
    'Toll kann ich das auch testen',
    'Toll kann ich das ausprobieren',
    'Toll kann ich das mal anprobieren',
    'Toll kann ich das mal ausprobieren',
    'Toll kann ich das mal testen',
    'Toll kann ich das testen',
    'Toll kann ich den anprobieren',
    'Toll kann ich den auch anprobieren',
    'Toll kann ich den auch ausprobieren',
    'Toll kann ich den auch testen',
    'Toll kann ich den ausprobieren',
    'Toll kann ich den mal anprobieren',
    'Toll kann ich den mal ausprobieren',
    'Toll kann ich den mal testen',
    'Toll kann ich den testen',
    'Toll kann ich die anprobieren',
    'Toll kann ich die auch anprobieren',
    'Toll kann ich die auch ausprobieren',
    'Toll kann ich die auch testen',
    'Toll kann ich die ausprobieren',
    'Toll kann ich die mal anprobieren',
    'Toll kann ich die mal ausprobieren',
    'Toll kann ich die mal testen',
    'Toll kann ich die testen',
  ]
};
