export default {
  slots: {},
  utterances: [
    'Darf ich das anprobieren',
    'Darf ich das auch anprobieren',
    'Darf ich das auch ausprobieren',
    'Darf ich das auch testen',
    'Darf ich das ausprobieren',
    'Darf ich das mal anprobieren',
    'Darf ich das mal ausprobieren',
    'Darf ich das mal testen',
    'Darf ich das testen',
    'Darf ich den anprobieren',
    'Darf ich den auch anprobieren',
    'Darf ich den auch ausprobieren',
    'Darf ich den auch testen',
    'Darf ich den ausprobieren',
    'Darf ich den mal anprobieren',
    'Darf ich den mal ausprobieren',
    'Darf ich den mal testen',
    'Darf ich den testen',
    'Darf ich die anprobieren',
    'Darf ich die auch anprobieren',
    'Darf ich die auch ausprobieren',
    'Darf ich die auch testen',
    'Darf ich die ausprobieren',
    'Darf ich die mal anprobieren',
    'Darf ich die mal ausprobieren',
    'Darf ich die mal testen',
    'Darf ich die testen',
    'Der sieht gut aus Darf ich das anprobieren',
    'Der sieht gut aus Darf ich das auch anprobieren',
    'Der sieht gut aus Darf ich das auch ausprobieren',
    'Der sieht gut aus Darf ich das auch testen',
    'Der sieht gut aus Darf ich das ausprobieren',
    'Der sieht gut aus Darf ich das mal anprobieren',
    'Der sieht gut aus Darf ich das mal ausprobieren',
    'Der sieht gut aus Darf ich das mal testen',
    'Der sieht gut aus Darf ich das testen',
    'Der sieht gut aus Darf ich den anprobieren',
    'Der sieht gut aus Darf ich den auch anprobieren',
    'Der sieht gut aus Darf ich den auch ausprobieren',
    'Der sieht gut aus Darf ich den auch testen',
    'Der sieht gut aus Darf ich den ausprobieren',
    'Der sieht gut aus Darf ich den mal anprobieren',
    'Der sieht gut aus Darf ich den mal ausprobieren',
    'Der sieht gut aus Darf ich den mal testen',
    'Der sieht gut aus Darf ich den testen',
    'Der sieht gut aus Darf ich die anprobieren',
    'Der sieht gut aus Darf ich die auch anprobieren',
    'Der sieht gut aus Darf ich die auch ausprobieren',
    'Der sieht gut aus Darf ich die auch testen',
    'Der sieht gut aus Darf ich die ausprobieren',
    'Der sieht gut aus Darf ich die mal anprobieren',
    'Der sieht gut aus Darf ich die mal ausprobieren',
    'Der sieht gut aus Darf ich die mal testen',
    'Der sieht gut aus Darf ich die testen',
    'Toll Darf ich das anprobieren',
    'Toll Darf ich das auch anprobieren',
    'Toll Darf ich das auch ausprobieren',
    'Toll Darf ich das auch testen',
    'Toll Darf ich das ausprobieren',
    'Toll Darf ich das mal anprobieren',
    'Toll Darf ich das mal ausprobieren',
    'Toll Darf ich das mal testen',
    'Toll Darf ich das testen',
    'Toll Darf ich den anprobieren',
    'Toll Darf ich den auch anprobieren',
    'Toll Darf ich den auch ausprobieren',
    'Toll Darf ich den auch testen',
    'Toll Darf ich den ausprobieren',
    'Toll Darf ich den mal anprobieren',
    'Toll Darf ich den mal ausprobieren',
    'Toll Darf ich den mal testen',
    'Toll Darf ich den testen',
    'Toll Darf ich die anprobieren',
    'Toll Darf ich die auch anprobieren',
    'Toll Darf ich die auch ausprobieren',
    'Toll Darf ich die auch testen',
    'Toll Darf ich die ausprobieren',
    'Toll Darf ich die mal anprobieren',
    'Toll Darf ich die mal ausprobieren',
    'Toll Darf ich die mal testen',
    'Toll Darf ich die testen',
  ]
};
